// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: category.sql

package db

import (
	"context"
)

const getCategoryList = `-- name: GetCategoryList :many
SELECT
  categories.category_id, categories.title, categories.created_at, categories.updated_at
FROM categories
ORDER BY created_at
`

func (q *Queries) GetCategoryList(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
