// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: goods_category.sql

package db

import (
	"context"
)

const createGoodsCategory = `-- name: CreateGoodsCategory :exec
INSERT INTO goods_categories(
  goods_id,
  category_id
) VALUES (
  $1, $2
)
`

type CreateGoodsCategoryParams struct {
	GoodsID    int32 `json:"goods_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) CreateGoodsCategory(ctx context.Context, arg CreateGoodsCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createGoodsCategory, arg.GoodsID, arg.CategoryID)
	return err
}

const deleteGoodsCategory = `-- name: DeleteGoodsCategory :exec
DELETE
FROM goods_categories
WHERE goods_categories.goods_id = $1
  AND goods_categories.category_id = $2
`

type DeleteGoodsCategoryParams struct {
	GoodsID    int32 `json:"goods_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) DeleteGoodsCategory(ctx context.Context, arg DeleteGoodsCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteGoodsCategory, arg.GoodsID, arg.CategoryID)
	return err
}
