// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGoods(ctx context.Context, arg CreateGoodsParams) (Good, error)
	CreateGoodsCategory(ctx context.Context, arg CreateGoodsCategoryParams) error
	CreateGoodsImage(ctx context.Context, arg CreateGoodsImageParams) (GoodsImage, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGoods(ctx context.Context, goodsID int32) error
	DeleteGoodsCategory(ctx context.Context, arg DeleteGoodsCategoryParams) error
	DeleteGoodsImage(ctx context.Context, goodsImageID int32) error
	GetCategoryList(ctx context.Context) ([]Category, error)
	GetGoods(ctx context.Context, goodsID int32) (GetGoodsRow, error)
	GetGoodsImageByUrl(ctx context.Context, arg GetGoodsImageByUrlParams) (GoodsImage, error)
	GetGoodsImageList(ctx context.Context, goodsID int32) ([]GoodsImage, error)
	GetGoodsList(ctx context.Context, arg GetGoodsListParams) ([]Good, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GetUser(ctx context.Context, userID int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateGoods(ctx context.Context, arg UpdateGoodsParams) error
	UpdateGoodsOnlyUpdatedAt(ctx context.Context, goodsID int32) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
